# Goal- to run End to End Devsecops CI pipline 

name: DevSecOps

on: 
    push:
        branches: [advanced]
        
jobs:
     
     # code stage (with shift left)
    code-qulity:
        uses: ./.github/workflows/code-quality.yml

    # secret scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # dependency check
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    # docker file lint and scan
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit 

    #sonarqube scan
    sonarqube-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    #code test
    code-test:
        uses: ./.github/workflows/code.test.yml
    # push to docker-hub
    docker-push:
        needs: [code-qulity,code-test, secret-scanning, dependency-scan, docker-checks, sonarqube-scan, code-test]
        uses: ./.github/workflows/Dockerpush.yml
        secrets: inherit

    ##-----------CD-------
    deploy:
        needs: [docker-push]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        


