# Goal- to run End to End Devsecops CI pipline 

name: DevSecOps

on: 
    push:
        branches: [advanced]
        
jobs:
     
     # code stage (with shift left)
    code-qulity:
        uses: ./.github/workflows/code-quality.yml

    # secret scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # dependency check
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    # docker file lint and scan
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit
