# Goal - Ensure the docker files and Docker images are security tested 

name: dcoekr scan

on: 
  workflow_call

jobs:
  docker-file-lint-and-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [backend, frontend]
        
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile:
  