# Goal - to check whether applications code coverage doesn't have security threats/issues

name: Sonar scan 
on:
  workflow_call:
jobs:
  sonarqube-scanner:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v7
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@8.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
